export const LOAD_PAGES_REQUEST = 'LOAD_PAGES_REQUEST';
export const LOAD_PAGES_SUCCESS ='LOAD_PAGES_SUCCESS';
export const LOAD_PAGES_FAILURE ='LOAD_PAGES_FAILURE';


export const INSERT_PAGES_REQUEST = 'INSERT_PAGES_REQUEST';
export const INSERT_PAGES_SUCCESS ='INSERT_PAGES_SUCCESS';
export const INSERT_PAGES_FAILURE ='INSERT_PAGES_FAILURE';

export const DEL_PAGES_REQUEST = 'DEL_PAGES_REQUEST';
export const DEL_PAGES_SUCCESS ='DEL_PAGES_SUCCESS';
export const DEL_PAGES_FAILURE ='DEL_PAGES_FAILURE';