export const LOAD_PAGES_REQUEST = 'LOAD_PAGES_REQUEST';
export const LOAD_PAGES_SUCCESS ='LOAD_PAGES_SUCCESS';
export const LOAD_PAGES_FAILURE ='LOAD_PAGES_FAILURE';


export const INSERT_PAGES_REQUEST = 'INSERT_PAGES_REQUEST';
export const INSERT_PAGES_SUCCESS ='INSERT_PAGES_SUCCESS';
export const INSERT_PAGES_FAILURE ='INSERT_PAGES_FAILURE';

export const DEL_PAGES_REQUEST = 'DEL_PAGES_REQUEST';
export const DEL_PAGES_SUCCESS ='DEL_PAGES_SUCCESS';
export const DEL_PAGES_FAILURE ='DEL_PAGES_FAILURE';

export const LOAD_REQUEST = 'LOAD_REQUEST';
export const LOAD_SUCCESS ='LOAD_SUCCESS';
export const LOAD_FAILURE ='LOAD_FAILURE';

export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS ='UPDATE_SUCCESS';
export const UPDATE_FAILURE ='UPDATE_FAILURE';